import type { ToolCategoryInfo } from './types'

export const TOOL_CATEGORIES: ToolCategoryInfo[] = [
  {
    id: 'productivity',
    slug: 'productivity',
    label: 'Productivity',
    description: 'Deep work, time blocking, goal breakdowns and daily planning systems.',
    icon: 'Zap',
    color: 'text-violet-400',
    bg: 'bg-violet-500/10',
  },
  {
    id: 'health-wellness',
    slug: 'health-wellness',
    label: 'Health & Wellness',
    description: 'Fitness planners, nutrition calculators, habit builders, and wellness roadmaps.',
    icon: 'Heart',
    color: 'text-rose-400',
    bg: 'bg-rose-500/10',
  },
  {
    id: 'finance',
    slug: 'finance',
    label: 'Finance',
    description: 'Budget builders, savings planners, debt payoff tools, and financial roadmaps.',
    icon: 'TrendingUp',
    color: 'text-emerald-400',
    bg: 'bg-emerald-500/10',
  },
  {
    id: 'education',
    slug: 'education',
    label: 'Education',
    description: 'Study planners, exam prep, reading plans, and learning roadmaps.',
    icon: 'BookOpen',
    color: 'text-sky-400',
    bg: 'bg-sky-500/10',
  },
  {
    id: 'career',
    slug: 'career',
    label: 'Career',
    description: 'Job search trackers, interview prep, career roadmaps, and skill planners.',
    icon: 'Briefcase',
    color: 'text-amber-400',
    bg: 'bg-amber-500/10',
  },
  {
    id: 'family-home',
    slug: 'family-home',
    label: 'Family & Home',
    description: 'Family schedules, household planners, chore systems, and home maintenance.',
    icon: 'Home',
    color: 'text-orange-400',
    bg: 'bg-orange-500/10',
  },
  {
    id: 'travel',
    slug: 'travel',
    label: 'Travel',
    description: 'Trip itineraries, travel budgets, packing lists, and vacation planners.',
    icon: 'MapPin',
    color: 'text-cyan-400',
    bg: 'bg-cyan-500/10',
  },
  {
    id: 'events',
    slug: 'events',
    label: 'Events',
    description: 'Wedding planners, party assistants, event budgets, and guest management.',
    icon: 'Calendar',
    color: 'text-pink-400',
    bg: 'bg-pink-500/10',
  },
  {
    id: 'personal-development',
    slug: 'personal-development',
    label: 'Personal Growth',
    description: 'Life goals, vision builders, 30-day challenges, and self-improvement roadmaps.',
    icon: 'Sparkles',
    color: 'text-indigo-400',
    bg: 'bg-indigo-500/10',
  },
  {
    id: 'business',
    slug: 'business',
    label: 'Business',
    description: 'Startup planners, marketing campaigns, project scopes, and business roadmaps.',
    icon: 'BarChart2',
    color: 'text-teal-400',
    bg: 'bg-teal-500/10',
  },
]
