import type { Template } from '@/features/templates/types'

export const groceryShoppingTemplate: Template = {
  id: 'tpl-033',
  slug: 'grocery-shopping',
  title: 'Grocery Shopping Checklist',
  description: 'A comprehensive weekly grocery checklist covering fresh produce, proteins, dairy, grains, store cupboard staples, and household essentials — never forget an item again.',
  category: 'family-home',
  type: 'checklist',
  featured: false,
  tags: ['grocery', 'shopping', 'food', 'household', 'meal prep'],
  previewImage: '/templates/previews/grocery-shopping.png',
  checklistDefaults: {
    mode: 'simple',
    items: [
      { id: 'ci-gs-1', text: 'Chicken breast (1.5 kg)', checked: false, order: 0, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-2', text: 'Minced beef (500 g)', checked: false, order: 1, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-3', text: 'Salmon fillets (4 pieces)', checked: false, order: 2, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-4', text: 'Eggs (12 free-range)', checked: false, order: 3, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-5', text: 'Milk (2 litres, semi-skimmed)', checked: false, order: 4, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-6', text: 'Greek yoghurt (500 g)', checked: false, order: 5, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-7', text: 'Cheddar cheese (300 g block)', checked: false, order: 6, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-8', text: 'Butter (250 g unsalted)', checked: false, order: 7, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-9', text: 'Broccoli (2 heads)', checked: false, order: 8, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-10', text: 'Spinach (200 g bag)', checked: false, order: 9, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-11', text: 'Cherry tomatoes (400 g punnet)', checked: false, order: 10, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-12', text: 'Cucumber (1 large)', checked: false, order: 11, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-13', text: 'Bell peppers — red, yellow, green (3)', checked: false, order: 12, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-14', text: 'Sweet potatoes (1 kg)', checked: false, order: 13, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-15', text: 'Carrots (1 kg bag)', checked: false, order: 14, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-16', text: 'Courgettes (3)', checked: false, order: 15, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-17', text: 'White onions (1.5 kg bag)', checked: false, order: 16, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-18', text: 'Garlic (1 bulb)', checked: false, order: 17, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-19', text: 'Bananas (6)', checked: false, order: 18, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-20', text: 'Apples (6 — Braeburn or Gala)', checked: false, order: 19, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-21', text: 'Avocados (4)', checked: false, order: 20, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-22', text: 'Lemons (3)', checked: false, order: 21, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-23', text: 'Wholegrain bread (800 g loaf)', checked: false, order: 22, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-24', text: 'Rolled oats (1 kg)', checked: false, order: 23, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-25', text: 'Brown rice (1 kg)', checked: false, order: 24, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-26', text: 'Pasta (500 g whole wheat)', checked: false, order: 25, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-27', text: 'Tinned chopped tomatoes (4 × 400 g)', checked: false, order: 26, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-28', text: 'Tinned chickpeas (2 × 400 g)', checked: false, order: 27, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-29', text: 'Extra virgin olive oil (500 ml)', checked: false, order: 28, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-30', text: 'Mixed nuts (200 g — almonds, walnuts, cashews)', checked: false, order: 29, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-31', text: 'Hummus (200 g tub)', checked: false, order: 30, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-32', text: 'Frozen peas (900 g bag)', checked: false, order: 31, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-33', text: 'Orange juice (1 litre — not from concentrate)', checked: false, order: 32, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-34', text: 'Sparkling water (6 × 500 ml)', checked: false, order: 33, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-35', text: 'Washing-up liquid', checked: false, order: 34, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-gs-36', text: 'Toilet roll (9-pack)', checked: false, order: 35, parentId: null, collapsed: false, depth: 0 },
    ]
  }
}
