import type { Template } from '@/features/templates/types'

export const travelPackingTemplate: Template = {
  id: 'tpl-036',
  slug: 'travel-packing',
  title: 'Travel Packing Checklist',
  description: 'Pack smart, travel stress-free. This comprehensive packing list covers clothing, toiletries, documents, electronics, and travel day essentials for any trip — short or long haul.',
  category: 'lifestyle',
  type: 'checklist',
  featured: false,
  tags: ['travel', 'packing', 'holiday', 'trip', 'luggage'],
  previewImage: '/templates/previews/travel-packing.png',
  checklistDefaults: {
    mode: 'simple',
    items: [
      { id: 'ci-tp-1', text: 'Passport — valid for 6+ months', checked: false, order: 0, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-2', text: 'Travel visa (if required for destination)', checked: false, order: 1, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-3', text: 'Flight / train tickets — printed and digital copies', checked: false, order: 2, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-4', text: 'Hotel / accommodation booking confirmation', checked: false, order: 3, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-5', text: 'Travel insurance policy and emergency numbers', checked: false, order: 4, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-6', text: 'Foreign currency or notify bank of travel dates', checked: false, order: 5, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-7', text: 'Debit card and credit card (plus a backup)', checked: false, order: 6, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-8', text: 'T-shirts and casual tops (1 per day + 1 spare)', checked: false, order: 7, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-9', text: 'Underwear (1 per day + 2 extra)', checked: false, order: 8, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-10', text: 'Socks (1 per day + 2 extra)', checked: false, order: 9, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-11', text: 'Trousers / shorts / skirts (2–3 bottoms)', checked: false, order: 10, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-12', text: 'One smart outfit for dinners or events', checked: false, order: 11, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-13', text: 'Lightweight jacket or layers for evenings', checked: false, order: 12, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-14', text: 'Comfortable walking shoes', checked: false, order: 13, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-15', text: 'Flip-flops or sandals (for beach, pool, or showers)', checked: false, order: 14, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-16', text: 'Swimwear (if applicable)', checked: false, order: 15, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-17', text: 'Pyjamas or sleepwear', checked: false, order: 16, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-18', text: 'Toothbrush and toothpaste', checked: false, order: 17, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-19', text: 'Shampoo, conditioner and body wash (travel-size)', checked: false, order: 18, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-20', text: 'Deodorant', checked: false, order: 19, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-21', text: 'Sunscreen (SPF 50)', checked: false, order: 20, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-22', text: 'Prescription medication with doctor\'s letter', checked: false, order: 21, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-23', text: 'Basic travel first aid kit — plasters, paracetamol, antihistamines', checked: false, order: 22, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-24', text: 'Laptop or tablet (if needed)', checked: false, order: 23, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-25', text: 'Smartphone and charger', checked: false, order: 24, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-26', text: 'Universal travel adapter', checked: false, order: 25, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-27', text: 'Portable phone charger / power bank', checked: false, order: 26, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-28', text: 'Headphones or earbuds', checked: false, order: 27, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-29', text: 'Download offline maps, shows and books', checked: false, order: 28, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-30', text: 'Day bag or small backpack for excursions', checked: false, order: 29, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-31', text: 'Reusable water bottle', checked: false, order: 30, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-32', text: 'Snacks for travel day (nuts, bars)', checked: false, order: 31, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-tp-33', text: 'Check luggage weight limits before leaving home', checked: false, order: 32, parentId: null, collapsed: false, depth: 0 },
    ]
  }
}
