import type { Template } from '@/features/templates/types'

export const weddingPlanningSystemTemplate: Template = {
  id: 'tpl-060',
  slug: 'wedding-planning-system',
  title: 'Wedding Planning System',
  description: 'Plan your perfect wedding without missing a detail. From venue booking to honeymoon, this comprehensive nested system covers every phase from engagement to the big day.',
  category: 'lifestyle',
  type: 'checklist',
  featured: true,
  tags: ['wedding', 'wedding planning', 'engagement', 'marriage', 'event'],
  previewImage: '/templates/previews/wedding-planning-system.png',
  checklistDefaults: {
    mode: 'advanced',
    items: [
      { id: 'ci-wps-1', text: '12+ Months Before: Foundations', checked: false, order: 0, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-wps-2', text: 'Set overall wedding budget', checked: false, order: 0, parentId: 'ci-wps-1', collapsed: false, depth: 1 },
      { id: 'ci-wps-3', text: 'Decide on wedding vision and style (formal, rustic, beach, etc.)', checked: false, order: 1, parentId: 'ci-wps-1', collapsed: false, depth: 1 },
      { id: 'ci-wps-4', text: 'Draft initial guest list', checked: false, order: 2, parentId: 'ci-wps-1', collapsed: false, depth: 1 },
      { id: 'ci-wps-5', text: 'Venue', checked: false, order: 3, parentId: 'ci-wps-1', collapsed: false, depth: 1 },
      { id: 'ci-wps-6', text: 'Research and visit at least 5 venues', checked: false, order: 0, parentId: 'ci-wps-5', collapsed: false, depth: 2 },
      { id: 'ci-wps-7', text: 'Confirm venue capacity fits guest list', checked: false, order: 1, parentId: 'ci-wps-5', collapsed: false, depth: 2 },
      { id: 'ci-wps-8', text: 'Book venue and pay deposit', checked: false, order: 2, parentId: 'ci-wps-5', collapsed: false, depth: 2 },
      { id: 'ci-wps-9', text: 'Get all venue rules and restrictions in writing', checked: false, order: 3, parentId: 'ci-wps-5', collapsed: false, depth: 2 },
      { id: 'ci-wps-10', text: 'Hire wedding planner or coordinator (if applicable)', checked: false, order: 4, parentId: 'ci-wps-1', collapsed: false, depth: 1 },
      { id: 'ci-wps-11', text: 'Book officiant / registrar for ceremony', checked: false, order: 5, parentId: 'ci-wps-1', collapsed: false, depth: 1 },

      { id: 'ci-wps-12', text: '9–12 Months Before: Key Vendors', checked: false, order: 1, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-wps-13', text: 'Photography & Videography', checked: false, order: 0, parentId: 'ci-wps-12', collapsed: false, depth: 1 },
      { id: 'ci-wps-14', text: 'Review portfolios of at least 6 photographers', checked: false, order: 0, parentId: 'ci-wps-13', collapsed: false, depth: 2 },
      { id: 'ci-wps-15', text: 'Meet with top 2–3 candidates', checked: false, order: 1, parentId: 'ci-wps-13', collapsed: false, depth: 2 },
      { id: 'ci-wps-16', text: 'Book photographer and videographer', checked: false, order: 2, parentId: 'ci-wps-13', collapsed: false, depth: 2 },
      { id: 'ci-wps-17', text: 'Catering', checked: false, order: 1, parentId: 'ci-wps-12', collapsed: false, depth: 1 },
      { id: 'ci-wps-18', text: 'Decide on catering style (sit-down, buffet, food stations)', checked: false, order: 0, parentId: 'ci-wps-17', collapsed: false, depth: 2 },
      { id: 'ci-wps-19', text: 'Taste test with at least 3 caterers', checked: false, order: 1, parentId: 'ci-wps-17', collapsed: false, depth: 2 },
      { id: 'ci-wps-20', text: 'Book caterer and confirm menu options', checked: false, order: 2, parentId: 'ci-wps-17', collapsed: false, depth: 2 },
      { id: 'ci-wps-21', text: 'Book florist and discuss floral theme', checked: false, order: 2, parentId: 'ci-wps-12', collapsed: false, depth: 1 },
      { id: 'ci-wps-22', text: 'Book band or DJ — watch live performance if possible', checked: false, order: 3, parentId: 'ci-wps-12', collapsed: false, depth: 1 },
      { id: 'ci-wps-23', text: 'Book hair and makeup artist — do trial run', checked: false, order: 4, parentId: 'ci-wps-12', collapsed: false, depth: 1 },

      { id: 'ci-wps-24', text: '6–9 Months Before: Attire & Details', checked: false, order: 2, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-wps-25', text: 'Wedding Attire', checked: false, order: 0, parentId: 'ci-wps-24', collapsed: false, depth: 1 },
      { id: 'ci-wps-26', text: 'Shop for wedding dress / suit — allow time for alterations', checked: false, order: 0, parentId: 'ci-wps-25', collapsed: false, depth: 2 },
      { id: 'ci-wps-27', text: 'Order wedding dress / suit and schedule fittings', checked: false, order: 1, parentId: 'ci-wps-25', collapsed: false, depth: 2 },
      { id: 'ci-wps-28', text: 'Choose and order bridesmaids / groomsmen attire', checked: false, order: 2, parentId: 'ci-wps-25', collapsed: false, depth: 2 },
      { id: 'ci-wps-29', text: 'Send invitations', checked: false, order: 1, parentId: 'ci-wps-24', collapsed: false, depth: 1 },
      { id: 'ci-wps-30', text: 'Design and order invitations', checked: false, order: 0, parentId: 'ci-wps-29', collapsed: false, depth: 2 },
      { id: 'ci-wps-31', text: 'Send invitations (6 months before)', checked: false, order: 1, parentId: 'ci-wps-29', collapsed: false, depth: 2 },
      { id: 'ci-wps-32', text: 'Set RSVP deadline (8 weeks before wedding)', checked: false, order: 2, parentId: 'ci-wps-29', collapsed: false, depth: 2 },
      { id: 'ci-wps-33', text: 'Create wedding website with details and registry', checked: false, order: 2, parentId: 'ci-wps-24', collapsed: false, depth: 1 },
      { id: 'ci-wps-34', text: 'Set up wedding gift registry', checked: false, order: 3, parentId: 'ci-wps-24', collapsed: false, depth: 1 },

      { id: 'ci-wps-35', text: '1–3 Months Before: Final Details', checked: false, order: 3, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-wps-36', text: 'Confirm final guest numbers with venue and caterer', checked: false, order: 0, parentId: 'ci-wps-35', collapsed: false, depth: 1 },
      { id: 'ci-wps-37', text: 'Ceremony Planning', checked: false, order: 1, parentId: 'ci-wps-35', collapsed: false, depth: 1 },
      { id: 'ci-wps-38', text: 'Write personalised vows', checked: false, order: 0, parentId: 'ci-wps-37', collapsed: false, depth: 2 },
      { id: 'ci-wps-39', text: 'Choose ceremony readings and music', checked: false, order: 1, parentId: 'ci-wps-37', collapsed: false, depth: 2 },
      { id: 'ci-wps-40', text: 'Arrange seating plan for reception', checked: false, order: 2, parentId: 'ci-wps-35', collapsed: false, depth: 1 },
      { id: 'ci-wps-41', text: 'Order wedding cake and confirm delivery', checked: false, order: 3, parentId: 'ci-wps-35', collapsed: false, depth: 1 },
      { id: 'ci-wps-42', text: 'Arrange transport (wedding car, guest shuttles)', checked: false, order: 4, parentId: 'ci-wps-35', collapsed: false, depth: 1 },
      { id: 'ci-wps-43', text: 'Book honeymoon flights and accommodation', checked: false, order: 5, parentId: 'ci-wps-35', collapsed: false, depth: 1 },
      { id: 'ci-wps-44', text: 'Final dress/suit fitting', checked: false, order: 6, parentId: 'ci-wps-35', collapsed: false, depth: 1 },

      { id: 'ci-wps-45', text: 'Week of the Wedding', checked: false, order: 4, parentId: null, collapsed: false, depth: 0 },
      { id: 'ci-wps-46', text: 'Confirm all vendors (time, location, access)', checked: false, order: 0, parentId: 'ci-wps-45', collapsed: false, depth: 1 },
      { id: 'ci-wps-47', text: 'Prepare wedding day emergency kit (sewing kit, stain remover, painkillers)', checked: false, order: 1, parentId: 'ci-wps-45', collapsed: false, depth: 1 },
      { id: 'ci-wps-48', text: 'Assign roles to bridesmaids / groomsmen for the day', checked: false, order: 2, parentId: 'ci-wps-45', collapsed: false, depth: 1 },
      { id: 'ci-wps-49', text: 'Rehearsal dinner — run through ceremony', checked: false, order: 3, parentId: 'ci-wps-45', collapsed: false, depth: 1 },
      { id: 'ci-wps-50', text: 'Get a good night\'s sleep the night before — enjoy the day!', checked: false, order: 4, parentId: 'ci-wps-45', collapsed: false, depth: 1 },
    ]
  }
}
